baseURL = "https://carlo-colombo.github.io/"
languageCode = "en-us"
title = "litblog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/carlo-colombo\">Carlo Colombo</a> 2021"

[params.social.config]
platforms = ["github","linkedin"]


[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.social]
github = "carlo-colombo"
linkedin = "carlocolombo"

[params.sections_left]
"/about" = "About me"


